version: '3.1'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    # 詳細はあんまわかってない。
    # ※ mongoのDBコンテナがreadyになる前に、接続しにいってるからかしら。ただ、dependsで依存性管理してもだめだった。
    # このコンテナからDBコンテナの初回接続時に必ずこけるので、restart alwaysが必要そう
    # restart alwaysだとdokcerデーモン起動時に、勝手に起動しちゃうのでひとまず別のオプションを試すことにした。
    # https://github.com/mongo-express/mongo-express-docker/issues/35#issuecomment-902809741
    # https://junchang1031.hatenablog.com/entry/2016/05/18/000605
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/